### PR TITLE
Support for Qgis 3.x

### LINKED ISSUE #6: Update to QGIS 3?
This is a really useful plugin, just wondered if it was planned to update it to one of the newer versions?

### PR DESCRIPTION
**Pull request by ThomasG77**
Need feedback as I'm not sure about the expected behaviour of the original plugin. PR related to https://gis.stackexchange.com/questions/337423/create-line-from-points-while-keeping-attribute-information. For people wanting to make feedback on the PR, you can try downloading temporary bundled zip for the plugin, install it as a ZIP within QGIS 3.0. URL for downloading https://labs.webgeodatavore.com/partage/pointstopaths.zip

Would close #6 when validated

### CODE REVIEW

**Comment by stuskier** [comment]
Thanks ThomasG77 for taking this on!  I downloaded your zip file and installed it as a plugin at 3.18.  I started the plugin and entered in the correct values.  **Immediately** upon clicking the _Output Shapefile > Browse_ button this error message appeared:

_2021-02-26T20:55:45     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details._

Here's the Python Error:

_2021-02-26T20:55:45     WARNING    Traceback (most recent call last):
              File "C:/Users/wagmo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pointstopaths\pointstopathsdialog.py", line 107, in outFile
              outFilePath = saveDialog(self)
              File "C:/Users/wagmo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pointstopaths\pointstopathsdialog.py", line 170, in saveDialog
              outFilePath = QtGui.QFileDialog.getSaveFileName(parent, parent.tr('Save output shapefile'), outDir, filter)
             AttributeError: module 'qgis.PyQt.QtGui' has no attribute 'QFileDialog'_

I don't know anything about Python, so I'm hoping you can solve the problem!  If it would help I can send you a small dataset, along with the plugin values I use.

Stu

**Comment by ThomasG77** [comment]
@stuskier You can try again. Code updated and zip on 1st link updated so you you can reinstall with latest code. If other issue, tell me or as suggested provide me a minimum sample (data + process to follow).
PS: For data, you may use existing one in the repo https://github.com/chiatt/pointstopaths/tree/master/test_data

**Comment by chiatt** [comment]
Thanks very much @ThomasG77 for submitting this PR and @stuskier for testing. I will try to test it out as well this weekend.

**Comment by stuskier** [comment]
When testing the repo data the previous error no longer appears, which is good.  However, this error now appears:

_2021-02-27T09:24:10     WARNING    Traceback (most recent call last):
              File "C:/Users/wagmo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pointstopaths\pointstopathsdialog.py", line 92, in accept
              points = processor.generatePointDict()
              File "C:/Users/wagmo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pointstopaths\processfeatures.py", line 45, in generatePointDict
              QgsMapLayerRegistry.instance().addMapLayer(self.layer)
             NameError: name 'QgsMapLayerRegistry' is not defined_

Here's a screenshot of the inputs:

Capture

**Comment by ThomasG77** [comment]
Fixed the issue mentioned and numerous other issues.
Tested with integer case, date case. For date, the right formatting rule format to work was `%Y-%m-%dT%H:%M`.

**Comment by stuskier** [comment]
Success, well done!  I tested it where the _Point Group Field_ was string or integer, and where the _Point Order Field_ was numeric or datetime.  Every situation gave the correct output.

While we're at it: what is the purpose of the _Gap Period (in minutes if order field is a datetime string)_ input, as highlighted in the screenshot below?  I've never used it, but in testing it doesn't seem to do anything.  Is it even written correctly?  Perhaps it should read _... if order field is_ **NOT** _a datetime string_???

Finally, when will this become part of the Official QGIS Plugin Repository?

Many thanks and congratulations, Bravo!

Captures

**Comment by ThomasG77** [comment]
Not sure exactly. It seems to be to draw lines using a gap interval to group all points within this gap. Need confirmation from @chiatt as I'm only doing an upgrade but do not know ins and outs of the plugin usage/intent.

**Review by chiatt — APPROVED** [review]
Works like a charm! Thanks again @ThomasG77 for taking this on.

**Comment by chiatt** [comment]
@stuskier Regarding the gap period - originally I was using this as a tool to inspect GPS trace data for wildlife. Sometimes the GPS would fail to record an animal's location for several hours. During these periods it would be impossible to know where the animal had moved, so I wanted to prevent the path from being continuous in those cases. So, the gap period is the number of minutes that you are willing to tolerate missing location data. You can test this with the `points_to_paths_test_input_v02.shp` file by setting the, group field to `txt_group`, the order field to `time_order` and the gap period to 60 minutes. You should see that bobcat now has two lines instead of one, breaking at the segment that exceeded 60 minutes.

Regarding getting this up on the QGIS plugin repository, I need to update some of the metadata and get it posted. I'll try to do that very soon. Thanks again for testing.

**Comment by stuskier** [comment]
@chiatt Thanks for the explanation, it now makes sense.

This is a very useful plugin. After running the tool, I make a new field in the point and lines layer. This field is a concatenation of the group field and the order field which is a unique id for each point. With this I join the point layer to the line layer and copy any additional point fields from point to line. With this, each line now contains point data. For example, I have point data containing aircraft data, such as altitude, airspeed, heading, etc. Following the join, those values are thus transferred to the line layer.

Great stuff! Stu

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stuskier** [comment]
May I make two suggestions?

1. Based on my testing, if the Line per vertex option is unchecked, Points to Paths provides identical functionality as does the core QGIS tool Points to Path. Thus there is duplication between the two tools. Because of this duplication, [I submitted a Github request](https://github.com/qgis/QGIS/issues/40677) last year to add the Line per vertex functionality to QGIS core. I'm not a programmer, so I don't know how a plugin becomes part of core, but I thought that I'd let you know that the feature request is out there.

2. Failing #1 above, may I suggest that you rename Points to Paths? That spelling is so similar to the core Points to Path name that I think a lot of users don't recognize the powerful difference. Perhaps a new name such as Points to Multiple Paths or Points to Line Segments would help differentiate.

Regards, Stu

**Comment by ThomasG77** [comment]
@stuskier For qgis/QGIS#40677, it requires much more as it's not Python code but C++. To give you more context, previously, a lot of processing tools native to QGIS were using Python, so improvements were easier to do. For performances reasons, most of them have been rewritten with C++ but it's less easy to contribute as you need C++ knowledge and not Python. For the evolution on QGIS code processing "Points to Path", changes have to happen at https://github.com/qgis/QGIS/blob/master/src/analysis/processing/qgsalgorithmpointstopaths.cpp

**Comment by stuskier** [comment]
Hello @ThomasG77 and @chiatt.  _Points to Paths_ continues to work fine.  However, it appears that people are having trouble finding it in the QGIS plugin repository because it is listed there as _PointstoPaths_, without spaces. Searching the repository for _Points to Paths_ comes up empty.  Would one of you please rename it in the repository to _Points to Paths_ for consistency?  Thanks!  For background see my comments at [https://gis.stackexchange.com/questions/418257/points-to-path-does-not-group-points-to-lines-in-qgis/418305?noredirect=1#comment681252_418305](url)

**Comment by stuskier** [comment]
Hello,

The QGIS plugin pointstopaths was updated to work with v. 3.x back in 2021 (please see below)

However, pointstopaths is no longer in the QGIS plugin repository. Has it been removed? If not, how can I access it?

TIA!

Stu
------- Original Message -------

**Comment by Kirkman** [comment]
@ThomasG77 @chiatt Just want to ask the same question as @stuskier -- PointsToPaths is no longer listed in the QGIS plugins repository. Was it removed? Can it be restored?

**Pull request merged**
